[package]
name = "setup"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
eyre.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
