[package]
name = "ctl"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
proto.workspace = true
setup.workspace = true

axum.workspace = true
chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true
